### ISSUE TITLE
Saucebot depricated?

### ISSUE THREAD

**Issue by biggestsonicfan** [rainyroads/discord-saucebot#8]
Just added the bot to my server and can only receive `The application did not respond` error messages, even to `/help`

Is the bot no longer functional and/or has development ceased?

**Comment by rainyroads** [comment]
Sorry about that, the bot should be back online now.

I plan to do some major updates to the bot sometime in the near future to make things a lot more stable and add in various improvements and new features at the same time.

If you experience any other issues, just let me know!
